[package]
name = "bindle"
version = "0.1.0"
authors = ["Matt Butcher <matt.butcher@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
toml = "0.5"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tempfile = "3.1"
sha2 = "0.9"
thiserror = "1.0"
semver = "0.11"
tokio = { version = "0.2", features = ["full"] }
warp = "0.2"
bytes = "0.5"
async-trait = "0.1"
futures = "0.3"
clap = "2.33"
reqwest = "0.10"

[[bin]]
name = "bindle-server"
path = "bin/server.rs"

[[bin]]
name = "bindle"
path = "bin/client.rs"

#[[bin]]
#name = "cargo2bindle"
#path = "bin/cargo2bindle.rs"

#[[bin]]
#name = "as2bindle"
#path = "bin/as2bindle.rs"