[package]
name = "bindle"
version = "0.1.0"
authors = ["Matt Butcher <matt.butcher@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
quiche = "0.5" # TODO: lock down to final version
toml = "0.5"
serde = {version = "1.0", features = ["derive"]}
tempfile = "3.1.0"
sha2 = "0.9.1"
thiserror = "1.0"