[package]
name = "bindle"
version = "0.1.0"
authors = ["Matt Butcher <matt.butcher@microsoft.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
toml = "0.5"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tempfile = "3.1"
sha2 = "0.9"
thiserror = "1.0"
semver = "0.11"
tokio = { version = "0.2", features = ["full"] }
# This can be upgraded to 0.5 once we upgrade tokio to 0.3 (which won't happen until hyper + warp do
# so)
tokio-util = "0.3"
warp = "0.2"
bytes = "0.5"
async-trait = "0.1"
futures = "0.3"
clap = "2.33"
reqwest = "0.10"
hyper = "0.13"

[dev-dependencies]
multipart = "0.17"
mime = "0.3"

[[bin]]
name = "bindle-server"
path = "bin/server.rs"

[[bin]]
name = "bindle"
path = "bin/client.rs"

[[bin]]
name = "cargo2bindle"
path = "bin/cargo2bindle.rs"

[[bin]]
name = "as2bindle"
path = "bin/as2bindle.rs"