[package]
name = "bindle"
version = "0.1.0"
authors = ["Matt Butcher <matt.butcher@microsoft.com>"]
edition = "2018"

[features]
default = ["server", "client"]
server = []
client = []

[dependencies]
anyhow = "1.0"
toml = "0.5"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tempfile = "3.1"
sha2 = "0.9"
thiserror = "1.0"
semver = { version = "0.11", features = ["serde"] }
tokio = { version = "0.2", features = ["full"] }
# This can be upgraded to 0.5 once we upgrade tokio to 0.3 (which won't happen until hyper + warp do
# so)
tokio-util = "0.3"
# Please node that many of these dependencies below this point that are out of date below here match
# the versions as used in other dependencies (such as warp or reqwest). So don't change them before
# the other crates change versions
warp = "0.2"
bytes = "0.5"
async-trait = "0.1"
futures = "0.3"
clap = "3.0.0-beta.2"
reqwest = { version = "0.10", features = ["stream"] }
hyper = "0.13"
url = "2.2"

[dev-dependencies]
multipart = "0.17"
mime = "0.3"

[[bin]]
name = "bindle-server"
path = "bin/server.rs"

[[bin]]
name = "bindle"
path = "bin/client.rs"

[[bin]]
name = "cargo2bindle"
path = "bin/cargo2bindle.rs"

[[bin]]
name = "as2bindle"
path = "bin/as2bindle.rs"
