[package]
name = "bindle"
version = "0.2.0"
authors = [
    "Matt Butcher <matt.butcher@microsoft.com>",
    "Taylor Thomas <taylor.thomas@microsoft.com>"
]
edition = "2018"
license-file = "LICENSE.txt"
description = "An aggregate object storage system for applications"
repository = "https://github.com/deislabs/bindle"
readme = "docs/crate-readme.md"
keywords = [
    "storage",
    "package",
]
exclude = [
    "docs/*",
    ".github/*",
    ".gitignore",
    "bin/",
    "test/"
]

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["server", "client", "caching", "test-tools"]
server = ["warp"]
client = ["reqwest", "mime_guess", "dirs"]
caching = ["client"]
test-tools = []
cli = ["clap"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
anyhow = "1.0"
toml = "0.5"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tempfile = "3.2"
sha2 = "0.9"
thiserror = "1.0"
semver = { version = "0.11", features = ["serde"] }
tokio = { version = "1.0", features = ["full"] }
tokio-util = "0.6"
tokio-stream = "0.1"
warp = { version = "0.3", features = ["tls"], optional = true }
bytes = "1.0"
async-trait = "0.1"
futures = "0.3"
clap = { version = "3.0.0-beta.2", optional = true }
reqwest = { version = "0.11", features = ["stream"], optional = true }
hyper = "0.14"
url = "2.2"
log = "0.4.11"
env_logger = "0.8"
dirs = { version = "3.0", optional = true }
mime_guess = { version = "2.0", optional = true }

[dev-dependencies]
mime = "0.3"

[[bin]]
name = "bindle-server"
path = "bin/server.rs"
required-features = ["cli"]

[[bin]]
name = "bindle"
path = "bin/client/main.rs"
required-features = ["cli"]

[[bin]]
name = "cargo2bindle"
path = "bin/cargo2bindle.rs"
required-features = ["cli"]

[[bin]]
name = "as2bindle"
path = "bin/as2bindle.rs"
required-features = ["cli"]
